type = glslang.EShLangFragment;
source = "";
source = core.add(source, "#version 150\n");
source = core.add(source, "out vec4 finalColor;\n");
source = core.add(source, "void main() {\n");
source = core.add(source, "    finalColor = vec4(1.0, 1.0, 1.0, 1.0);\n");
source = core.add(source, "}");
glslang.initialize();
shader = new glslang.Shader(type, source);
binary = shader.data();
disassembly = shader.disasm();
system.log(disassembly);
system.log(binary);
shader.delete();
glslang.finalize();