a=1;
system.println(a);
b=2.0;
system.println(b);
c="Hello World!";
system.println(c);
d=[1,2.0];
system.println(d);
e=[];
system.println(e);
f=[[1,2],[3,4]];
system.println(f);
g=[[5,6],[7,8]];
system.println(g);
h={a: 1,b: 2.0,"c": "Hello World!"};
system.println(JSON.stringify(h));
i={};
system.println(JSON.stringify(i));
j=1;
system.println(j);
k=1;
system.println(k);
